Revert "defconfig: Add UAPI_HEADER_TEST for Lahaina GKI"
Not sure why, but HDRTEST fails on up to date Fedora 43:

In file included from <built-in>:1:
In file included from ./usr/include/linux/lightnvm.h:23:
In file included from /usr/include/stdio.h:440:
/usr/include/bits/floatn.h:97:9: error: __float128 is not supported on this target
   97 | typedef __float128 _Float128;
      |         ^
  HDRTEST usr/include/linux/seccomp.h
1 error generated.

Furthermore, this option is not enabled on holi anyway.

This reverts commit 589f2a3e90c28acca23b88307657a59841f42d80.

Change-Id: Iafc01a807d1f033aacd25cd311002229ec74a7e7